name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out the latest Source code from master
        uses: actions/checkout@v2
      - name: Setting Up Node JS 18 Version
        uses: action/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --prefix client
